name: core-nestjs
on:
  push:
    branches:
      - main 

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm install
      - run: tsc && npm publish
    env:
      NODE_AUTH_TOKEN: ${{secrets.PUBLISH_SECRET}}